// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh6wufp0msYsQaOvfqTm-n-jQhdlWbmg0',
    appId: '1:463431603925:web:603b386ce4aab29bd5b45c',
    messagingSenderId: '463431603925',
    projectId: 'bio-track-a6dba',
    authDomain: 'bio-track-a6dba.firebaseapp.com',
    storageBucket: 'bio-track-a6dba.appspot.com',
    measurementId: 'G-YQ59DH4YWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeMbpj_andxiIl7jfsFkCbAF-1VJK5EDA',
    appId: '1:463431603925:android:be79866cdcda37bfd5b45c',
    messagingSenderId: '463431603925',
    projectId: 'bio-track-a6dba',
    storageBucket: 'bio-track-a6dba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZoyXq0V-3Rr65GQlt1cdFH5bEcl8Jvks',
    appId: '1:463431603925:ios:f6c39a2e122cd52fd5b45c',
    messagingSenderId: '463431603925',
    projectId: 'bio-track-a6dba',
    storageBucket: 'bio-track-a6dba.appspot.com',
    iosBundleId: 'com.kbyai.facerecog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZoyXq0V-3Rr65GQlt1cdFH5bEcl8Jvks',
    appId: '1:463431603925:ios:da7f1c61baa749c5d5b45c',
    messagingSenderId: '463431603925',
    projectId: 'bio-track-a6dba',
    storageBucket: 'bio-track-a6dba.appspot.com',
    iosBundleId: 'com.example.facerecognitionFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh6wufp0msYsQaOvfqTm-n-jQhdlWbmg0',
    appId: '1:463431603925:web:0f8817f13aa35b9ad5b45c',
    messagingSenderId: '463431603925',
    projectId: 'bio-track-a6dba',
    authDomain: 'bio-track-a6dba.firebaseapp.com',
    storageBucket: 'bio-track-a6dba.appspot.com',
    measurementId: 'G-ZTG2WLRG08',
  );
}
